# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml



stages:
  - test
  - doc


# Use cargo to test the project
test:latest:
  stage: test
  image: rust:latest
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose -- --test-threads=1
  tags:
    - rust
  artifacts:
    expire_in: 1 week

# Use cargo to generate doc
gendoc:
  stage: doc
  image: rust:latest
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo doc
  tags:
    - rust
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week
