# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml



stages:
  - build
  - test

# Use cargo to test the project
test:latest:
  stage: build
  image: rust:latest
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose -- --test-threads=1
  tags:
    - rust


test:report:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo install junitify
    - cargo test -- --test-threads=1 --format=json -Z unstable-options --report-time | junitify --out $CI_PROJECT_DIR/tests/
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/tests/*.xml
  tags:
    - rust

#deploy:
#  stage: deploy
#  script: echo "Define your deployment script!"
#  environment: production
